version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Chemin vers le dossier contenant le Dockerfile backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  # Chemin vers le dossier contenant le Dockerfile frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
